### ISSUE TITLE
imrnc not working. 

### ISSUE THREAD

**Issue by Lavkushwaha** [nathvarun/Custom-React-Native-Snippets-Unsure-Programmer#2]
![screenshot 180](https://user-images.githubusercontent.com/13220405/42418594-622a8010-82c1-11e8-9d97-80996236ff66.png)
![screenshot 181](https://user-images.githubusercontent.com/13220405/42418595-626bb67a-82c1-11e8-8a11-85a7afac0113.png)

**Comment by nathvarun** [comment]
Try and place the contents in javascript.json.


On 8 Jul 2018 15:13, Lav Kushwaha <notifications@github.com> wrote:

[screenshot 180]<https://user-images.githubusercontent.com/13220405/42418594-622a8010-82c1-11e8-9d97-80996236ff66.png>
[screenshot 181]<https://user-images.githubusercontent.com/13220405/42418595-626bb67a-82c1-11e8-8a11-85a7afac0113.png>

**Comment by sysdev-jay** [comment]
yes,  worked. Thanks, @nathvarun
